spring:
    profiles: local
    mvc:
        view:
           prefix: /WEB-INF/jsp/
           suffix: .jsp
    http:
        encoding:
            charset: UTF-8
            enable: true
        force: true
    datasource:
#       url: jdbc:mariadb://127.0.0.1:3306/root1 #hikaridatasource 사용시 이름이 jdbc-url로 변경 
#       driver-class-name: org.mariadb.jdbc.Driver
#       jdbc-url: jdbc:mariadb://localhost:3306/root1
#       username: root1
#       password: tmax@23
       hikari:
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3306/root1
          username: root1
          password: root1
          connectionTimeout: 5000
          validationTimeout: 1000
          maximumPoolSize: 10
    kafka:
     consumer:
        bootstrap-server: localhost:9092
        group-id: sgicmsa
        auto-offset-reset: latest
        #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        #value-deserializer: org.apache.kafka.common.serialization.StringSerializer
     producer:
        bootstrap-server: localhost:9092          
          
mybatis:  
    configuration:    
      multiple-result-sets-enabled: false
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      jdbc-type-for-null: varchar
      default-fetch-size: 500
    configLocation: classpath:mybatis-config.xml 
    mapper-locations:
      - classpath:mybatis/mapper/*.xml 
---
spring: 
    profiles: dev
    mvc:
        view:
           prefix: /WEB-INF/jsp/
           suffix: .jsp
    http:
        encoding:
            charset: UTF-8
            enable: true
        force: true
    datasource:
       #url: jdbc:mariadb://10.96.107.215:3306/root1 #hikaridatasource 사용시 이름이 jdbc-url로 변경 
       #driver-class-name: org.mariadb.jdbc.Driver
       #jdbc-url: jdbc:mariadb://10.96.107.215:3306/root1
       #username: root1
       #password: tmax@23
       hikari:
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://172.21.2.11:3306/root
          username: root
          password: tmax@23
          connectionTimeout: 5000
          validationTimeout: 1000
          maximumPoolSize: 10
          autoCommit: false
          
    kafka:
     consumer:
        bootstrap-server: 10.96.19.128:9092:9092
        group-id: sgicmsa
        auto-offset-reset: latest
        #key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        #value-deserializer: org.apache.kafka.common.serialization.StringSerializer
     producer:
        bootstrap-server: 10.96.19.128:9092:9092              
         
mybatis:  
    configuration:    
      multiple-result-sets-enabled: false
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      jdbc-type-for-null: varchar
      default-fetch-size: 500
    configLocation: classpath:mybatis-config.xml 
    mapper-locations:
      - classpath:mybatis/mapper/*.xml 
