spring:
    profiles: local
    mvc:
        view:
           prefix: /WEB-INF/jsp/
           suffix: .jsp
    http:
        encoding:
            charset: UTF-8
            enable: true
        force: true
    datasource:
#       url: jdbc:mariadb://127.0.0.1:3306/root1 #hikaridatasource 사용시 이름이 jdbc-url로 변경 
#       driver-class-name: org.mariadb.jdbc.Driver
#       jdbc-url: jdbc:mariadb://localhost:3306/root1
#       username: root1
#       password: tmax@23
       hikari:
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://localhost:3306/root1
          username: root1
          password: tmax@23
          connectionTimeout: 5000
          validationTimeout: 1000
          maximumPoolSize: 10
mybatis:  
    configuration:    
      multiple-result-sets-enabled: false
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      jdbc-type-for-null: varchar
      default-fetch-size: 500
    configLocation: classpath:mybatis-config.xml 
    mapper-locations:
      - classpath:mybatis/mapper/*.xml 
---
spring: 
    profiles: dev
    mvc:
        view:
           prefix: /WEB-INF/jsp/
           suffix: .jsp
    http:
        encoding:
            charset: UTF-8
            enable: true
        force: true
    datasource:
       #url: jdbc:mariadb://10.96.107.215:3306/root1 #hikaridatasource 사용시 이름이 jdbc-url로 변경 
       #driver-class-name: org.mariadb.jdbc.Driver
       #jdbc-url: jdbc:mariadb://10.96.107.215:3306/root1
       #username: root1
       #password: tmax@23
       hikari:
          driver-class-name: org.mariadb.jdbc.Driver
          jdbc-url: jdbc:mariadb://10.96.107.215:3306/root1
          username: root1
          password: tmax@23
          connectionTimeout: 5000
          validationTimeout: 1000
          maximumPoolSize: 10
          autoCommit: false
mybatis:  
    configuration:    
      multiple-result-sets-enabled: false
      map-underscore-to-camel-case: true
      call-setters-on-nulls: true
      jdbc-type-for-null: varchar
      default-fetch-size: 500
    configLocation: classpath:mybatis-config.xml 
    mapper-locations:
      - classpath:mybatis/mapper/*.xml 